### ISSUE TITLE
[rdf] Storing ids

### ISSUE THREAD

**Issue by rickskyy** [G-Node/python-odml#111]
The question appeared with the way of storing ids. As long as we are using uuids, should we store them as UUID objects (created by uuid python module) or convert them into strings after initialization?

**Comment by rickskyy** [comment]
I think the most convenient way is store them as strings, because we do not use any methods withing UUID objects.

**Comment by mpsonntag** [comment]
Achilleas and me would be for just storing the string.

**Comment by mpsonntag** [comment]
Discussion about implementing a public setter for ids can be found [here](https://github.com/G-Node/python-odml/pull/113/files#r127918058).
