### ISSUE TITLE
Version converter tool

### ISSUE THREAD

**Issue by jgrewe** [G-Node/python-odml#122]
compare #120 for a start

**Comment by jgrewe** [comment]
Requirements:
* use argparse or equivalent to provide command line options
* allow to specify input and output files
* if input file is a directory, work on all files in that directory
* allow for recursive operations

**Comment by rickskyy** [comment]
I think if an input file is a directory, the tool should only convert top level files (not triggering subdirectories). I added optional argument `-sub`, which is used for indication that all files have to be processed.
What do you think?

**Comment by jgrewe** [comment]
I agree with hndling only 1st level files if not explicitely stated otherwise. I would prefer to use a ```-r``` argument  for recursive, as is common for command line tools.

**Comment by mpsonntag** [comment]
Fixed with the introduction of a dedicated version converter script in PR #302
