### ISSUE TITLE
Extend merge function - Add 'overwrite' functionality

### ISSUE THREAD

**Issue by achilleas-k** [G-Node/python-odml#127]
Currently merging is conservative (strict) and will not overwrite conflicting information.

New function should allow conflicting information to be overwritten.
Merge should also be possible on the Document (root) level.

When performing `A.merge(B)`, we should allow specifying a merge strategy for conflicting information (e.g., Sections with the same name and type at the same level):
- `skip`: keeps the original information (`A` takes priority)
- `overwrite`: keeps the information coming from the merge (`B` takes priority)
- `keepboth`: renames conflicting information coming from `B` and stores it alongside the corresponding information in `A`.

**Comment by mpsonntag** [comment]
Has been differently resolved via #275.
