### ISSUE TITLE
Keeping a source attribute for metadata values

### ISSUE THREAD

**Issue by lzehl** [G-Node/python-odml#130]
Currently (in v1.3) the value objects have a `reference` and a `filename` attribute. 

We are still using the `filename` attribute to state where the metadata value in the property was generated/extracted from (mostly filenames of the metadata source files). Values belonging to one property always come from the same source. but the values of different properties in one section can come from different sources.

For v1.4 the possibility to state the source file/device of a metadata value should be kept in parallel to the  `reference` attribute in which one could state a reference url to a terminology or ontology.
The naming could be made in v1.4 more explicit, e.g.: `source` or `metadata_source`.

**Comment by mpsonntag** [comment]
After a brief discussion the suggested name that stuck best to describe the use case was `value_origin`. If there are no complaints we will add this field to `property` when moving to odml v1.4.
