### ISSUE TITLE
Retrieving complete terminology does not work

### ISSUE THREAD

**Issue by lzehl** [G-Node/python-odml#135]
Using the code in #74 for v1.3 will result in the following error for `doc2 = doc1.get_terminology_equivalent()`:
`AttributeError: 'NoneType' object has no attribute 'sections'`

Also trying to set a repository for a section (`sec.repository=repo_sec`) will result in:
`Failed to load http://portal.g-node.org/odml/terminologies/v1.0/carmenMini/carmen_mini.xml due to parser errors`

**Comment by jgrewe** [comment]
has been fixed in the terminologies
