### ISSUE TITLE
Restructure of terminology repository

### ISSUE THREAD

**Issue by lzehl** [G-Node/python-odml#136]
The terminology repository should be restricted to (one layer) sections with properties.

More complex structures (odML trees) should be moved to a new template store.
For improving the usage of templates see  #137.

**Comment by mpsonntag** [comment]
Terminology and template repositories have been created and have been split; terminologies and templates are now handled and deployed from there:
- [odml-terminologies](https://github.com/G-Node/odml-terminologies)
- [odml-templates](https://github.com/G-node/odml-templates)
