### ISSUE TITLE
Example SPARQL queries

### ISSUE THREAD

**Issue by mpsonntag** [G-Node/python-odml#142]
We need to verify, that the current RDF schema we export to can be nicely queried.

For this it would suggest to
- [ ] create an example python script in `doc/example_rdfs` where two or more odML RDF files from the gin-odml data repository are loaded and merged into a graph.
- [ ] come up with example SPARQL queries and run them using RDFlib just printing the results via the example script

**Comment by jgrewe** [comment]
Something could be (in the sql world):

```select d.* from dataset d, stimulus s where s.contrast = '20%'```

or
```select d.* from dataset d, stimulus s, cell c where s.contrast = '20%' and c.celltype='P-unit'```

This is, of course more interesting when there would be more than one file :) 
Will export some more soon...
