### ISSUE TITLE
Subclassing Sections

### ISSUE THREAD

**Issue by mpsonntag** [G-Node/python-odml#146]
Subclass Sections according to the type of available odml terminologies and start with the Section types in our odml example files. Update the current odML ontology with these terms as new subclasses for class Section.

That way e.g. a Section of type `electrode` can be found either by `a Section & hasType=Electrode` or directly by `a Electrode` which should make the queries more efficient when they become more complex.

I guess the actually subclassing in OWL will look something e.g. for Stimulus or Electrode:

        owl:Class rdf:type odml:Stimulus
            rdfs:subClass of odml:Section;
        
        owl:Class rdf:type odml:Electrode
            rdfs:subClass of odml:Section;

Some representative examples for the `Section.type` found in `relacs_export`, `drosophila` and `spike_lfp` which should be subclassed are

        stimulus
        subject
        Cell properties
        Recording
        Preparation
        Cell
        Setup
        hardware
        DataAcquisition
        dataset
        settings
        electrode
        collection/hardware_settings

**Comment by rickskyy** [comment]
Want to make clear some points:

1. Basically we will need to add all existing Section subclasses available in [http://portal.g-node.org/odml/terminologies/v1.0/terminologies.xml](). Am I right?
2. How do you like adding link to actual terminology in `rdfs:seeAlso` subclass annotations? I think it will be valuable.

```
:Stimulus rdf:type owl:Class ; 
     rdfs:subClassOf odml:Section ;
     rdfs:comment "Description of the class";
     rdfs:label "Stimulus" ;
     rdfs:seeAlso http://portal.g-node.org/odml/terminologies/v1.0/stimulus/stimulus.xml.
```
