### ISSUE TITLE
odml and odml-gui availibility with (ana)conda with Python 3 support: Install documentation

### ISSUE THREAD

**Issue by msuzen** [G-Node/python-odml#158]
### Related issues:
1.  `odml` is not available via `conda`. Creating a g-node channel would be nice.  See [custom channels](https://conda.io/docs/custom-channels.html)
2.  `odml-gui` works with apt-get installation well with python 2.7 but not within anaconda.
3.  Python 3 support for both.
4.  Documenting these.

###  odml-gui via Ubuntu distribution works
 `odml-gui` works well via Ubuntu distribution well, (v2.7.x). Here are the steps
```bash
sudo apt-get install python-gtk2
pip install enum
pip install enum34
pip install odml
``` 
Then `/usr/local/bin/odml-gui`. Le voilà !

###  odml-gui via conda distribution does not work: gtk import issue
Installation in anaconda 2.7 environment for odml
```bash
/home/nobody/anaconda3/envs/p27/bin/pip install odml
````
But `gtk` is not "importable", tried all different channels, they seem to install gtk.
```bash
 /home/nobody/anaconda3/envs/p27/bin/conda install -c mw gtk2 
```
but still getting `ModuleNotFoundError: No module named 'gtk'`.

**Comment by jgrewe** [comment]
We are about to release a version 1.3 of the core library without the ui soon. This is then python3 compatible. 

The ui was moved into a separate [repository](https://github.com/g-node/odml-ui) and will depend on the version 1.3 branch of the lib. It uses pygtk3 and we will have to try with anaconda.

**Comment by mpsonntag** [comment]
Has been resolved via [odml-ui PR 82](https://github.com/G-Node/odml-ui/pull/82)
