### ISSUE TITLE
Check format version on open/load

### ISSUE THREAD

**Issue by achilleas-k** [G-Node/python-odml#180]
I checked if we're doing this and as far as I can tell there are no checks.
Since we have odML format version strings in our files, we should use them! Each parser should check the version when loading. What we do if there's a mismatch can be discussed but I think there are a few options to consider:
1. Silently convert to the new version and return the upgraded tree.
2. Convert to the new version with a warning and return the upgraded tree.
3. Throw an error and suggest that the user run the conversion tool on the file.

In either case, I don't think we should overwrite or change the file without the user explicitly making a call to the write/save command. I'm generally opposed to writing to files when a load command is executed.

**Comment by mpsonntag** [comment]
I'd go for option 2) + not writing to file.

**Comment by mpsonntag** [comment]
As discussed, we will go with option 3). In addition we provide an auto-convert flag to the parser document loading which is `false` by default but can be used to automatically convert to version 1.1 on document loading.

**Comment by achilleas-k** [comment]
Also as discussed, we should make a v1.3 library release that checks the file format version string and throws an error if the file version is v1.1.

**Comment by mpsonntag** [comment]
Closed via #197 and #198.
