### ISSUE TITLE
RDFWriter broken on install

### ISSUE THREAD

**Issue by mpsonntag** [G-Node/python-odml#212]
Currently the RDFWriter is broken when odml is installed, since a required file `doc.section_subclasses.yaml` is not exported on install.

**Comment by mpsonntag** [comment]
Issue was not fixed with #325.

**Comment by fschrader1992** [comment]
This could be fixed by moving the file into the odml directory. The question is, where exactly, either in the odml/tools folder, odml itself or into a new folder odml/resources, where other files could be stored as well.

**Comment by mpsonntag** [comment]
I would either use a folder `odml/resources` or `odml/tools/resources` and move the file `doc/section_subclasses,yaml` there.

**Comment by achilleas-k** [comment]
I agree, resources would be a better location.  Keep the resources separate from the code directories.

**Comment by jgrewe** [comment]
:+1: for a resources folder, I guess I would try to keep it flat and vote for ```odml/resources```

**Comment by achilleas-k** [comment]
Right, should have specified `odml/resources` is my vote too.
