### ISSUE TITLE
Handling of Empty and None values in dtype.py lead to load errors

### ISSUE THREAD

**Issue by mpsonntag** [G-Node/python-odml#245]
The value handling of lists of "empty" values in `dtypes.py` lead to different results and 
potentially broken odML documents:

- int and float replace None by default values. Can be saved and loaded.

    `prop = odml.Property(name="int", value=[""], dtype="int")`
    leads to `prop.value` ... `[0]`

    `prop = odml.Property(name="float", value=[None, None], dtype="float")`
    leads to `prop.value` ... `[0.0, 0.0]`

- string related dtypes (string, text, url, person) replace None by "None". Can be saved and loaded.

   `prop = odml.Property(name="str", value=["", None], dtype="string")`
    leads to `prop.value` ... `['', 'None']`

- bool, date, time and datetime save None to file but leads to an Error that is hard to identify when the file is loaded.

    `prop = odml.Property(name="date", value=[None], dtype="date")`
    leads on document load to `ValueError: odml.Property.value: passed values are not of consistent type!`

**Comment by mpsonntag** [comment]
Should we consistently
- return the defined dtype default value if an assigned list value is "" or None?
or
- handle the currently broken dtypes case by case - since e.g. returning the current date for every "" or None entry might be annoying as well.

**Comment by lzehl** [comment]
hi! I would vote for the first solution: always return the default dtype for "" or None

**Comment by jgrewe** [comment]
I agree, return default value. Or, we could return None for any non-existing value

**Comment by mpsonntag** [comment]
- If we return the default value, for date, time and datetime this will always be "now", for bool it will be False.
- If we return None we need to handle this differently on load, currently it leads to an error.

My vote is to always return the default value.

**Comment by jgrewe** [comment]
ok, let's do it
