### ISSUE TITLE
Rename 'id' variables

### ISSUE THREAD

**Issue by achilleas-k** [G-Node/python-odml#268]
When setting entity UUIDs we use the name `id` for the argument in the setter. This isn't nice since `id` is a builtin function. This doesn't cause any major issues since the scope of the functions where it's used is rather small. It's also understandable to use the name `id` for the keyword argument in the `set_id()` method and something like `id_` would be ugly.

We could instead use the name `uuid`, or something like `eid` (for entity ID), or `oid` (object ID). Another idea might be `sid` (Section ID) and `pid` (Property ID). This would just be for the keyword argument in the `set_id()` method and anywhere else the word `id` might appear as a non-attribute.

Thoughts and suggestions welcome.

**Comment by mpsonntag** [comment]
My favorite would be `oid`!
