### ISSUE TITLE
Property handling

### ISSUE THREAD

**Issue by JuliaSprenger** [G-Node/python-odml#272]
Currently it is possible to add anything to the ```properties``` list of a section without any check being performed.
This way 

- non ```odml.Property``` objects can be inserted into the odml structure (eg  ```sec.properties[0] = 'blaa'```)
- inserted ```odml.Property``` objects are not linked properly (eg. ```sec.properties[0] = odml.Property(name='myprop', value=3)``` results in ```sec.properties[0].parent``` is None)

Would it make sense to implement a similar functionality here as used for ```value``` lists in #237?

**Comment by mpsonntag** [comment]
This should indeed be caught, thx!

**Comment by mpsonntag** [comment]
And the same is true for `sec.sections` and `doc.sections`.
