### ISSUE TITLE
type handling for uncertainties

### ISSUE THREAD

**Issue by JuliaSprenger** [G-Node/python-odml#294]
For generation of an odML document, the type of the uncertainty can be arbitrary. However, when saving & reloading the uncertainty is always a string. Maybe it would make sense to do the conversion to string already when generating the odML to ensure consistency between newly generated odML objects and reloaded ones.

**Comment by achilleas-k** [comment]
Is there a reason it's stored as a string in the file?

**Comment by achilleas-k** [comment]
Linking to G-Node/nixpy#319

**Comment by achilleas-k** [comment]
## It has been decided that uncertainty will be limited to `float`
