### ISSUE TITLE
version converter: incomplete string conversion

### ISSUE THREAD

**Issue by JuliaSprenger** [G-Node/python-odml#295]
The representation of strings in odml file version 1.1 is using quotation marks around individual string value entries. These are not added using the version converter, resulting in the splitting if single values containing commata in odml file version 1.0 to multiple values in odml file version 1.1.

An example file can be found here https://web.gin.g-node.org/INT/multielectrode_grasp/src/master/datasets/l101210-001.odml for the 'Location' property in the 'Setup' section.

**Comment by mpsonntag** [comment]
It seems that its not the `VersionConverter` that creates the issue, but rather that the `xmlparser` does not work properly in extracting single entry strings containing commata.

Even if a single string value with commata is wrapped in quotation marks, the value still is chopped up at each comma.
