### ISSUE TITLE
version converter incorrect hint

### ISSUE THREAD

**Issue by JuliaSprenger** [G-Node/python-odml#317]
When trying to load an odml file version 1.0 with odml version 1.4.2 the resulting error message states 
```
odml.tools.parser_utils.InvalidVersionException: Cannot parse odML document with format version '1'. 
	Use the 'tools.VersionConverter' to import previous odML formats.
```
However, the version converter can not be used as described above, but needs to be explicitely imported from the submodule:
```python
from odml.tools.version_converter import VersionConverter
```
Probably the VersionConverter should be linked in the `odml.tools.__init__.py`?

**Comment by achilleas-k** [comment]
I agree with adding `VersionConverter` in `odml.tools.__init__.py`.

**Comment by achilleas-k** [comment]
Looks like this isn't as simple as I thought.  @mpsonntag tells me the current module structure is quite complicated and putting classes at the module level very quickly leads to import cycles.  For now we should fix the error message, but in the long run we should reorganise the modules to make things a bit more sane.
