### ISSUE TITLE
check jsonparser

### ISSUE THREAD

**Issue by lzehl** [G-Node/python-odml#32]
- Is it necessary to keep it?
- If yes, it seems to work differently from xmlparser: it would be nice if the user could use same commands. 
- Should it be seperated from the xmlparser? Or would it be nicer to have one saving and loading package?

**Comment by mohit-0212** [comment]
Both json, xml are good. Json is as powerful as xml, maybe even more, plus it is easier, and simpler to parse once we get used to it.

It works using almost the similar commands,  
like in xml parser, writing was like: `odml.tools.xmlparser.XMLWriter(obj).write_file(path)`
in Json parser it is like: `odml.tools.jsonparser.JSONWriter(obj).write_file(path)`

Similarly for printing the output as in xml/json format.

I have implemented this in my #76 . But I'm getting an error while loading using json parser, which for the time being I have commented out, but I will soon resolve it.

**Comment by jgrewe** [comment]
imho, we should keep it and make them working the same way. I might further be desirable to have a yaml or also nix output backend in the future.

**Comment by mohit-0212** [comment]
Yes, that is what I intended.
I have just implemented an easier load, save, display for backends of xml, json.
Just have one error which I have stated there in my lates commit at #76 .

**Comment by lzehl** [comment]
The functionality of the jsonparser needs to be checked for odML v1.2 and v1.3.

**Comment by jgrewe** [comment]
closed via #152
