### ISSUE TITLE
value vs. values

### ISSUE THREAD

**Issue by lzehl** [G-Node/python-odml#38]
Hi, 
while writing the tutorial I'm constantly stumbling over the way how one can access value objects which are attached to properties. Two ways are working "value" and "values".
If only one value is attached to the property, directly the value object is returned in the first case, and a list is returned in the second case:
`p = odml.Property('myProp', value=odml.Value(4, dtype=odml.DType.int))`
`p.value`
`<int 4>`
`p.values`
`[<int 4>]`
If more values are attached to the property both cases give back a list:
`p.append(odml.Value(2, dtype=odml.DType.int))`
`p.value`
`[<int 4>, <int 2>]`
`p.values`
`[<int 4>, <int 2>]`
Could we not make the whole thing simpler, in just having the opportunity to call "values" and always return a list?
Best, Lyuba

**Comment by lzehl** [comment]
@jgrewe can we close this issue now? It was solved with your PR some months ago, correct?

**Comment by jgrewe** [comment]
@lzehl indeed, I guess this can be closed ;)
