### ISSUE TITLE
remove mapping functionality

### ISSUE THREAD

**Issue by jgrewe** [G-Node/python-odml#48]
remove the mapping fields

remove the mapping functionality

check for proxy model necessity

**Comment by achilleas-k** [comment]
I think I am going to remove the proxy model completely. From what I've seen so far, beyond its use in the mapping functionality, it's only used in the GUI. It would probably be best if the Proxy module was transferred to the GUI repo eventually.

I might be getting carried away with my eagerness to delete stuff though, so let me know if you think it should stay.

**Comment by jgrewe** [comment]
go ahead, I came to the same conclusion.
