### ISSUE TITLE
disallow multiple values in one property

### ISSUE THREAD

**Issue by jgrewe** [G-Node/python-odml#49]

**Comment by lzehl** [comment]
Hi @jgrewe, 
I realized that this issue will have a large impact on our odML structures. 
Why do you want to disallow multiple Values for Properties? 
I completely agree with restricting the Values contained in a Property to one data type, which is something we did already in our odML structures. 
But having multiple Values attached to one Property was so far quite useful for us, e.g., for ranges, or more importantly for specifying specific subsection of the complex tree structure (e.g., names of the used channels).
