### ISSUE TITLE
looking for bugs to get started

### ISSUE THREAD

**Issue by kapilkd13** [G-Node/python-odml#54]
Hi,
I am kapil. I am interested in python-odml project and would like to work on it. To get easy with code base and understand code flow, I was looking for some bug fixes that I can make. It would be great if you can point me to those bugs with a little help on where I need to look in the code base to fix those issues.
Also is there a IRC channel through which we can communicate.

I have build the python-odml project on my local machine and have gone through the tutorial provided in there.
Thanks.

**Comment by jgrewe** [comment]
Hi @kapilkd13,

thanks for your interest, we will have an internal discussion soon and create some issues that you could work on.

**Comment by kapilkd13** [comment]
Hi @jgrewe 
That would be great.
Thanks.
