### ISSUE TITLE
how to reach odml editor 

### ISSUE THREAD

**Issue by kapilkd13** [G-Node/python-odml#55]
I followed the instructions given  in the readme file to build the project. Using the instructions I successfully installed the odml python library and it is working perfectly. But still I couldn't find instructions to reach odml GUI editor. 
Please help me build the odml editor(I need to build the software from source for my requirement).
I would have asked this on stackOverflow with odml tag, but odml tag doesn't exist on stackoverflow and I don't have enough reputation to create new tag.

**Comment by gicmo** [comment]
The editor component has been removed from the source with commit 1d81b15. I would need to be resurrected into an external project, be updated to depend on `python-odml` and most importantly being [ported](https://wiki.gnome.org/Projects/PyGObject/IntrospectionPorting) from PyGTK to [PyGObject](https://wiki.gnome.org/Projects/PyGObject/IntrospectionPorting). But I am not up to date when it comes to the current plan and roadmap anymore so I leave it to the team to comment about the it.

**Comment by lzehl** [comment]
for odML v1.3 see: https://github.com/G-Node/odml-ui
