### ISSUE TITLE
Update documentation after removing entities

### ISSUE THREAD

**Issue by achilleas-k** [G-Node/python-odml#58]
Documentation and tutorials should be updated to reflect all the removed features:
- Multiple values not allowed: #49 
- Value fields filename, checksum, and encoder removed: #50 
- Mapping functionality removed: #48

**Comment by lzehl** [comment]
@achilleas-k: If you like I can work on updating the documentation and the tutorials.

**Comment by jgrewe** [comment]
Hi @lzehl that would be most welcome :)

**Comment by lzehl** [comment]
Could one of you let me know which branch I need to pull? I started having a look at the branch unusedfields from achilleas-k, and was surprised that I could still attach more than one Value to a Property...

**Comment by jgrewe** [comment]
That issue is not yet solved, @achilleas-k just removed the unused fields of the values. The multiple values is on my list :)

**Comment by achilleas-k** [comment]
There's also the [mapping-rm](https://github.com/achilleas-k/python-odml/tree/mapping-rm) branch I'm currently working on where I remove the mapping code. That's ahead of the `unusedfields` branch but might not build and test properly.

Just mentioning it in case you want to keep an eye on the progress.

**Comment by lzehl** [comment]
I just wanted to let you know that I would prefer updating the documentation when you merged the changes into the main branch. Would that work for everyone?

**Comment by achilleas-k** [comment]
Yes, I think that's a good idea.
