### ISSUE TITLE
Throw an exception if a property is attempted to append to Document object

### ISSUE THREAD

**Issue by msuzen** [G-Node/python-odml#69]
If `Document` object can not have properties `append` should throw an exception if a property is used as an argument.

**Comment by jgrewe** [comment]
I agree, this should not happen. The document is just the embracing entity that should offer only some basic document related information.

**Comment by msuzen** [comment]
This is a bit more complicated than I though, adding checks on objects, see pull #75, make validation tests fail. The following check makes unit tests on validation fail:

```python
 from odml.section import BaseSection
 if not isinstance(obj_tuple[i], BaseSection):
       raise KeyError("Object " + str(obj_tuple[i]) + " is not a Section.")
```

**Comment by msuzen** [comment]
This is resolve with the pull request #78 that is merged.
