### ISSUE TITLE
error at importing terminology

### ISSUE THREAD

**Issue by jpresern** [G-Node/python-odml#73]
Failed to load http://portal.g-node.org/odml/terminologies/v1.0/terminologies.xml due to parser errors
 "Start tag expected, '<' not found, line 1, column 1"

**Comment by jpresern** [comment]
It seems that downloaded terminologies.xml is downloaded and saved with b'<?  instead of <? 
Python3 issue?

Adding .decode() to data = urllib2.urlopen(url).read().decode() in terminology.py parses the file correctly but as a consequence downloaded terminologies.xml are split into 38 xml files, each of which throws following warning:

warning[http://portal.g-node.org/odml/terminologies/v1.0/analysis/psth.xml:175:<value>]: cannot set 'dtype' property on <value>: AttributeError("'binary' is not a valid type.",)

**Comment by jgrewe** [comment]
Hi @jpresern, it seems you are using the head of master. We removed the support for binary files in the  values with pr #57. The terminologies for version 1 contain several properties that suggest "binary" content... Need to move the terminologies to comply with the model changes...

**Comment by lzehl** [comment]
@jpresern and @jgrewe 
Yes, I already discovered this warning! Due to the changes and updates of odML, several terminologies are outdated. It's not only the 'binary' values, but also the use of other deprecated attributes, I think. Sorry, I did not raise an issue for this already...
