### ISSUE TITLE
Presence of escape characters in strings

### ISSUE THREAD

**Issue by digaru19** [G-Node/python-odml#81]
If escape characters like `\n` , `\t` , etc. are present in strings like the `version` , `author` , `description` , `name` , etc. , they are evaluated as such, i.e. `\n` actually produces a newline when the object is printed, or even when it is written to the *.odml* file. 

```
doc = odml.Document(author="Katy\nicole", version="1.1a\todo(1.2)")
print(doc)
```
gives -
```
<Doc 1.1a	odo(1.2) by Katy
icole (0 sections)>
```
And when written to a file, the output is as shown -
```
  <version>1.1a    odo(1.2)</version>
  <author>Katy
icole</author>
```

If this is an undesired behaviour and needs to be fixed, I will like to work on it.

**Comment by achilleas-k** [comment]
Working as intended.
