### ISSUE TITLE
odml-editor

### ISSUE THREAD

**Issue by Vutsuak16** [G-Node/python-odml#87]
The odml editor on loading a valid odml document does not include the relevant details like:
1.date
2. author

should it include those fields?

**Comment by mohit-0212** [comment]
The odml editor GUI displays all the details when a document is loaded.
On the other hand, for CLI odml editor, for print(doc), we can see the author's name, as can be seen in the __repr__ method.
`def __repr__(self):
        return "<Doc %s by %s (%d sections)>" % (self._version, self._author, len(self._sections))`
Although the date is not included here, which can be seen by 'doc.date'. It can be included in the method as you say, but wouldn't make much of a difference. No harm in including anyway.

I hope I was clear and interpreted your query correctly. :)
