### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by Vutsuak16** [G-Node/python-odml#88]
@lzehl  could you have a look at the following issues:

1.Since file,checksum,encoder have already been removed should we remove them from the documentation too?
![capture](https://cloud.githubusercontent.com/assets/10365536/24089620/bae747ee-0d5e-11e7-85b2-a035830ecf35.PNG)
2. Mapping has also been scraped out..and the documentation needs updating.

![capture2](https://cloud.githubusercontent.com/assets/10365536/24089630/dfba0d22-0d5e-11e7-84ee-9786d4bdfdd8.PNG)

**Comment by mohit-0212** [comment]
Also, updating regarding the recent pull request of No multiple values. #66

**Comment by lzehl** [comment]
@vutsuak16 and @mohit-0212: I'm on it :) I should have an updated version of the tutorial at latest by  tomorrow!

**Comment by lzehl** [comment]
@vutsuak16: I'm sorry for the delay I was interrupted with meetings. I'm finishing a first draft of the tutorial this morning. I originally wanted to wait until all new developments are integrated but I think I'll do a PR for this version. This way we have a tutorial online that covers the most prominent changes. The PR will be ready around noon.

**Comment by lzehl** [comment]
@jgrewe with you closing issue #97, I think we can close this issue too! 
BTW: thanks for cleaning up my commit mess :) and sorry again!
