### ISSUE TITLE
introduce a unique identifier (uoid) for each odml object

### ISSUE THREAD

**Issue by msuzen** [G-Node/python-odml#94]
following discussion from #93,setting `uoid` (unique object id) when an object is created. Use case could be that this can be used in `reference` or in setting `parent` attribute. Maybe a `SHA-1` string.

**Comment by lzehl** [comment]
There is currently a Section attribute called ``id``... not sure if this was attended to be used for something like this?

**Comment by msuzen** [comment]
c.f. #45  too.

**Comment by msuzen** [comment]
@lzehl Maybe `uuid` is a better name.

**Comment by mpsonntag** [comment]
Has been resolved since #121
